language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- ant run-tests
script:
- ant
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
notifications:
  slack:
    secure: S4uvycQsk8CwrzRq+nd/jm0zgefGN1kds7eISES9YqA2qqA1JLGP14ha/zlzt26Q8ROyyt0eVpEWYhot4x6uW10GkT5DCXl3hXyauFBBwVzYmqgRnrv5B44e6eQ2t3AQD5U9Fs4WyubGKFohmAZOPq3A16fRyUwrAySR8aV/blFQ7w7uKt7ZDaBTSxhfsG85a+7Whose0eANdx2ikR8C//BEYmTBkoLDoja6r4U/kbEtX/7sQ+14/80hiZX1Lh4+oFk+kP6YSV1Qw5BcIoOpjTqsDoyzA0TYd3qaMmYX7BcdDSXuE9XRf+DhIy6WQAKM+5rafJcm1t6V33DQ23F9RD5teC0VrmpfoZmSK0MF9Dbi/PEEbnGdABf68l0kLpU/1GXZrgde2dWA7JW+s+JhvqwsZdatzmLKchD/8lLf9xJfWCu+S3SwPiTt8sCDwgTXIiqEBKS4+DyHkj0oH3Qdm4fWS604r9nLnuRa668EPGH1ONLFwMIQ/MhlY1ofO5Cmy8E5+7gBzDdAzVbQp2jRbDTDLxOEIGtQsF3I2T+3Keeoqo/pUFKQrZgk0JEqswcbpaK/0WahyKTBU48h6fkU/PPosy1EFuXqCn+cD29Ha9eEf9Q3tRr7DBxecfS28GF+Q3zJt9eHJkcqXny72/H1tQITg3NTuHLU03xX4ZYOp5o=
  email: false
