language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- ant run-tests
script:
- ant
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: huqo0J7jcmGB7kLqKOo+NqhbDu3StYoKvKng1VdxwHwrIcvnBWBh6KKSdfdeoHUopv/EGoJK9R8ztghDpGiZwE8kaLGBk9YYvtVoFav2t237tdSP7B3WrUHkomG3sJi36IxPLyX4FxPyLE13vgq16Q5lDv4aOQ+NcdQCT4+7RGVjsta5e3FalnLvgkRIag2DU3BvusIWK0zhjx2J3xeIJDvIp8Ric1nPFD3Tc5yleTlOhb6y6Qxcvwb0umvzpuCxwEzzIEN9/fc0vvleN16WYftzx4G3RFuVyoQMESuWI3QxHTGRg7n2PZPHhABQzTkjNiYSe4foKlb733CCfTkzPy4XPA8PLvE0fo+zh00wC7czgA1cFxvynceKbToNg9ftGXymFV8B6p/rC+5unPSVcbwrrJHaGtwncnjiP2e07oUvNx+eTSvOvgVK53NmHFg8KtVaMcEP2Trw3C/yOQSsfKCUkHXin6oByHHzKvc9mtIx23W4RgBsf96nnO3gdamkGFnBzc1NkwoseQ4BgB2wTZJCzlQJ3bmDNux0lD4iwaYc17XE4WhJsOskaQ+XFcC4HM13BnVVKEYVrBDVz5uwIj6/aJ/hUKRWZj7AB3WxvId1cD7wrQC/Ej9bdVeuYyVIQxFlrChFKx4m4Z+q2x0oiz7M0UuKA3WZeBN5tkimKJs=
  email: false
